name: Deploy to GitHub Pages (docs/)

on:
  push:
    branches:
      - main
    # don’t re-trigger when docs/ changes
    paths-ignore:
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # so we can push back to main
          persist-credentials: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build site into docs/
        run: npm run build   # your vite.config.ts already has outDir: "docs"

      - name: Add 404 fallback for SPA routing
        run: cp docs/index.html docs/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: main    # we’re updating docs/ on main
          destination_dir: docs   # put files under docs/ so your src/ stays intact
          force_orphan: false
